/*
-- Query: SELECT * FROM bddfal.insgines
LIMIT 0, 1000

-- Date: 2017-11-23 14:53
*/
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (1,'a + palme simple','Le faluchard','Agrégation','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (2,'Abeille','GM/GC','Travail et minutie associatif','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (3,'Aigle','Le faluchard','Amour de l\'aviation ou brevet de pilote','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (4,'Ancre','Le faluchard','Amour de la navigation','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (5,'Bacchus','GM/GC','Dignité dans l\'ivresse (retournable/retirable)','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (6,'Ballon de foot','Le faluchard','Amour des sports collectifs','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (7,'Bêta','Le faluchard','Bac ES','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (8,'Bettrave','GM/GC/3 anciens','Cunnilingus','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (9,'Bouteille de bordeaux','GM/GC','Cuite certifiée','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (10,'Bouteille de Champagne','GM/GC','Coma éthylique certifiée','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (11,'C','Le faluchard','Capacité','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (12,'c suivie de palme','Le faluchard','CAPES','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (13,'Carotte','GM/GC/3 anciens','Acte valeureux','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (14,'Chameau','Le faluchard','A l\'endroit : célibataire','A l\'envers : dans l\'antichambre du marriage','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (15,'Chardon','Le faluchard','Originaire de Lorraine','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (16,'Chauve souris','GM/GC','Nuit blanche pour motif associatif','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (17,'Chouette','GM/GC','Oiseau de nuit','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (18,'Choufleur','GM/GC/3 anciens','Partouze','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (19,'Cigogne','Le faluchard','Originaire d\'Alsace','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (20,'Ciseaux','Le faluchard','Faluche cousue soi même','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (21,'Ciseaux à une branche','Le faluchard','Faluche pas cousue soi même','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (22,'Clé de sol','GM/GC','Digne chanteur de paillardes','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (23,'Cochon','Le faluchard','A l\'endroit : a intégré','A l\'envers : a été intégré','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (24,'Cocotte en papier','Le faluchard','Grand sécheur devant l\'éternel','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (25,'Coq','GM/GC','Grande gueule sachant l\'ouvrir','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (26,'Comète','Le faluchard','Amour de l\'astronomie','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (27,'Cor de chasse','GM/GC','Grand chasseur devant l\'éternel','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (28,'Cupidon','Le faluchard','Fiancé','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (29,'DAEU','Le faluchard','DAEU ( Diplôme d\'Accès aux Etudes Universitaires )','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (30,'Drapeau','Le faluchard','Année d\'étude à l\'étranger ( sous l\'étoile )','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (31,'e','Le faluchard','Année validée par équivalence','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (32,'Ecureuil','Le faluchard','Membre d\'une junior association','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (33,'Épée','Le/La partenaire','Fin baiseur','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (34,'Épervier','Le/La partenaire','Chasseur de pigeon à main nues','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (35,'Epi de blé','Le faluchard','Radin','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (36,'Epi de blé sur ruban de sainté','Le faluchard','Satin Radin','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (37,'Epi de blé croisé faucille','Le faluchard','Chanceux aux examens','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (38,'Epsilon','Le faluchard','Bac S math ou physique','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (39,'Etoile argentée','Le faluchard','Année redoublée','VP étudiant d\'UFR ou CA d\'IUT','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (40,'Etoile dorée','Le faluchard','Année d\'étude débutée','VP étudiant d\'université','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (41,'Etoile dorée sur ruban d\'élu et ruban bleu','Le faluchard','Élu mutualiste','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (42,'Etoile et foudre','Le faluchard','Amour de l\'informatique ou électronique/électricité','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (43,'FAUX','Le faluchard','Passage de vis à trépas lors de la garde d\'un étudiant en santé','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (44,'Flèche','Le faluchard','Éjaculateur précoce','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (45,'Fer à cheval','Le faluchard','Chanceux aux examens','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (46,'Feuille de vigne','Le faluchard','Perte de la virginité masculine','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (47,'Fleur de lys','Le faluchard','Scout','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (48,'Flying penis/foufoune','Le faluchard','Étudiant en kiné ayant sarsouillé dans une salle de massage','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (49,'Fourchette','Le faluchard','Amour des plaisirs de la tables','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (50,'Fourchette sur ruban bleu','GM/GC','Cordon bleu','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (51,'Fraise','La falucharde','Enceinte','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (52,'Grappe de raisin','Le faluchard','Amour du bon vin','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (53,'Grenouille argentée','Le faluchard','Élu au conseil UFR','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (54,'Grenouille dorée','Le faluchard','élu au conseil de l\'université','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (55,'Hache','GM/GC','Prise de guerre (ne pas confondre avec vandalisme)','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (56,'Hermine','Le faluchard','Breton','Danseur du Limousin','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (57,'i','Le faluchard','(après bac) Bac international','Dagobit simple','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (58,'intiales','Le faluchard','Bac selon les initiales','Élu conseil (hors tortue et grenouille)','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (59,'Lapin','Le faluchard','Chaud lapin','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (60,'Lime','Le/La partenaire','Acte laborieux','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (61,'Lion dressé','Le faluchard','Originaire du Lyonnais','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (62,'Lion héraldique','Le faluchard','Originaire de Normadie','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (63,'Lyre','Le faluchard','Amour de la musique','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (64,'Mamouth','GM/GC','Gardien des traditions','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (65,'M d\'or','Le faluchard','Misère','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (66,'Navet','GM/GC/3 anciens','Enculage','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (67,'Nounours','Le faluchard','A l\'endroit : gros dormeur','A l\'envers : dors en cours','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (68,'Pachyderme','GM/GC','Personne lourde','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (69,'Palette vernie','Le faluchard','Amour de la peinture','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (70,'Palme double','Le faluchard','Obtention d\'un diplôme','Remerciement pour le travail d\'une année dans l\'asso','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (71,'Palme large','Le faluchard','Major de promotion','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (72,'Palme simple','Le faluchard','Fin de cycle sans diplôme','Remerciement pour un travail bien mené dans l\'asso','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (73,'Parapluie fermé','Le faluchard','A vomi dans sa faluche','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (74,'Parapluie ouvert','Le faluchard','A vomi dans sa faluche et l\'a remise','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (75,'Pendu','Le faluchard','Marié ou pacsé','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (76,'Pensée ou Orchidée','Le/La partenaire','Experte en la matière','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (77,'Phi','Le faluchard','Bac L','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (78,'Phi-Epsilon','Le faluchard','Bac S SVT','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (79,'Plume','Le faluchard','Amour de la littérature','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (80,'Poireau','GM/GC/3 anciens','Pipe dûement accomplie','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (81,'Poule','GM/GC','Personne très chaude','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (82,'Quille','Le faluchard','Service militaire','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (83,'Tête de mort','Le faluchard','Abandon de la discipline','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (84,'Tête de vache','Le faluchard','Réussite aux rattrapages','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (85,'Tomate','GM/GC/3 anciens','Acte valeureux malgré l\'indisposition de Madame','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (86,'Tortue dorée','Le faluchard','Élu CROUS','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (87,'Tortue dorée','Le faluchard','Élu CNOUS','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (88,'Raquette','Le faluchard','Amour des sports individuels','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (89,'Rose','Le faluchard','Perte de la virginité féminine','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (90,'Sanglier','Le faluchard','Originaire des Ardennes','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (91,'Singe','GM/GC','Quémandeur d\'insigne','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (92,'Sphinx','Le faluchard','Polyglotte','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (93,'Squelette','Le faluchard','A l\'endroit : amour de l\'anatomie (matière)','A l\'envers jambes ouvertes : amour des femmes','A l\'envers jambes ouvertes : amour des hommes');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (94,'Sou troué','GM/GC','Nuit passée au poste pour motif étudiant','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (95,'Tastevin','Le faluchard','Originaire de Bourgogne','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (96,'Taureau','Le faluchard','Sur ruban bleu : parent d\'un garçon','Sur ruban rose : parent d\'une fille','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (97,'Volant','Le faluchard','Conducteur de fin de soirée (on brise un bout par accident)','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (98,'Voilier','Le faluchard','Amour de la navigation ou permis bateau','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (99,'X','Le faluchard','Dagobit croisé','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (100,'W','Le faluchard','Dagobit multiple (>2)','','');
INSERT INTO `insgines` (`id_insgines`,`insigne`,`decernement`,`sens1`,`sens2`,`sens3`) VALUES (101,'','','','','');
